export const ENV_CONFIG_KEYS = {
  // App
  NODE_ENV: 'NODE_ENV',
  APP_PORT: 'APP_PORT',
  APPLICATION: 'APPLICATION',

  // Database
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
  DB_SCHEMA: 'DB_SCHEMA',
  DB_SYNC: 'DB_SYNC',
  DB_LOG: 'DB_LOG',

  // Encryption & JWT
  ENCRYPTION_SECRET_KEY: 'ENCRYPTION_SECRET_KEY',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_EXPIRES_IN_MILLISECOND: 'JWT_EXPIRES_IN_MILLISECOND',
  JWT_REFRESH_EXPIRES_IN_MILLISECOND: 'JWT_REFRESH_EXPIRES_IN_MILLISECOND',

  // Mail
  MAIL_HOST: 'MAIL_HOST',
  MAIL_PORT: 'MAIL_PORT',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',
  MAIL_SENDER: 'MAIL_SENDER',

  // OTP
  OTP_EXPIRES_IN_MINUTES: 'OTP_EXPIRES_IN_MINUTES', // e.g., 10
  OTP_LENGTH: 'OTP_LENGTH', // e.g., 6

  // CORS / Frontend
  FRONTEND_URL: 'FRONTEND_URL', // e.g., "http://localhost:5173"
};
